### ISSUE TITLE
Crossorigin is down

### ISSUE THREAD

**Issue by Themandunord** [technoboy10/crossorigin.me#57]
https://crossorigin.me/https://google.com Error 502
The server is down ?

**Comment by joker314** [comment]
And https://crossorigin.me/ is technically down too, though it does load with the disclaimer at the top: `This page (https://crossorigin.me/) is currently offline. However, because the site uses CloudFlare's Always Online™ technology you can continue to surf a snapshot of the site. We will keep checking in the background and, as soon as the site comes back, you will automatically be served the live version. Always Online™ is powered by CloudFlare | Hide this Alert`

**Comment by CosmicWebServices** [comment]
It is back up

**Comment by joker314** [comment]
Yup
