### ISSUE TITLE
Implement POST requests

### ISSUE THREAD

**Issue by Hardmath123** [technoboy10/crossorigin.me#6]
> No, and I'm pretty sure it shouldn't. If crossorigin.me supported those verbs, you could do some pretty messed up stuff.

That's, uh, not how it works. The requests would be sent from your end, and as you said, you don't forward cookies (even if you _did_, what's the worst they could do?).

In any case, nobody really uses PUT and DELETE anymore. People just gave up on the whole "semantic HTTP" thing and use GET/POST for everything—if you're lucky, they pay attention to idempotency.

POST requests, by the way, would be incredibly useful, since so many APIs listen to them.

Oh, and while I'm at it about security: you should either enable a legit SSL cert on your domain (non-free with Heroku) or tell folks that they can use `atcors.herokuapp.com` for secure connections. Otherwise they're open to mitming (again, what's the worst they can do?).

**Comment by technoboy10** [comment]
1) Yeah, POST would be a good idea I guess - I'm just worried about people doing sketchy stuff with requests besides GET and crossorigin.me getting the blame. I'm open to suggestions.

2) I have an SSL cert from namecheap, but I can't set that up with heroku :(

**Comment by Hardmath123** [comment]
What sketchy stuff do you expect? (Also, you can write a disclaimer to un-get blame.)

**Comment by ansarizeeshan** [comment]
Please tell us *...*.herokuapp.com so that we can use it for secured request

**Comment by technoboy10** [comment]
@ansarizeeshan atcors.herokuapp.com

**Comment by technoboy10** [comment]
- [x] HTTPS support
- [ ] POST request support
@Hardmath123 convince me about POST request stuff and I'll add it.

**Comment by Hardmath123** [comment]
I don't see why you would choose not to. You should be asking someone to convince you not to do it.

**Comment by schme16** [comment]
@Hardmath123: Reasons I can think of not to support it by default:
 - Adds quite a lot of complexity to the codebase (not an end user concern, but a concern none the less)
 - Opens the server up to being thrashed by overly large POST packets (I'm thinking 50mb+ files, etc; possible mitigation: hard limit the file sizes...?)
 - With POST open there might be increased legal responsibilty (depending on your juristiction) as someone with stolen or ill-gotten log in credentials could use this server to hide their attack vector (as on the other side it would look like the 'attacker' was the crossorigin.me server; mitigations: ???)

I'm not necessarily against the idea of POST support, per se, but would definitely love to hear your thoughts on the issues above (and feel free to add things I've not considered, and their mitigation strategies)

**Comment by tanx** [comment]
First of all thanks for providing crossorigin.me. Very Useful!

+1 for POST requests. I need them for uploading PGP public keys to SKS servers (which don't support CORS atm) from the web.

> @Hardmath123 convince me about POST request stuff and I'll add it.

Great! Any news on the progress. How can I help to test?

Thanks!

**Comment by intval** [comment]
> Adds quite a lot of complexity to the codebase 
Actually the other way around. Limiting the verbs requires more code than to leave a default / single code path for all scenarios. Depends on implementation though, but implementation might be more efficient, for example if proxy is done with nginx configuration and requires zero programming at all.

> With POST open there might be increased legal responsibilty
People who hide their attack vector use a vpn or better else someone's else computer. The law doesn't distinguish between get and post 


> Opens the server up to being thrashed by overly large POST packets
The server is opened for being trashed by many many small packets at the moment. Substituting it with few big packets ain't any different. Though limit on packet size and duration of transmission should be configured.
For an attacker it's economically more efficient to produce many small packages, rather than few big (as he has a limit on network as well), because he can capitalize on the overhead each connection costs the server

> Post is more risky for site owners
Not true. It depends on the security of the site itself and as many sites are vulnerable regardless of the http verb used. It's up to the site developers to use CSRF protection and whatever else. 

> crossorigin.me can be used for attacking websites
True, but, its an economically poor decision. Whoever will want to attack someone's site is more likely to hide their ass behind a serious proxy, use someone's else computer (botnet) or some other service specifically meant for this needs. Performing an attack via crossorigin.me is a bad idea, as crossorigin.me will end up the server under attack and crash the chain first before reaching the final destination or just slow down attack attempts.

> Why this site exists?
You wanted to provide comfort for the users, but well, avoiding 10 out 11 http verbs doesn't make the use of the service much comfortable. Remember that the problem you are solving is browsers who impose weird error messages *on the client side*. Using any other tool (like postman) or 'curl' from cli doesn't impose this restrictions and the effect on destination api-server side is the same. Therefore you are solving a client-side problem, and clients, hereby, ask to implement POST :)

+ thanks for the service

**Comment by intval** [comment]
Bah, looked at the code
Taking my words back. Implementing POST will add a bit of code

**Comment by herohamp** [comment]
posts requests would be nice but people could use that to try and send Gigabytes through your servers and if you have an bandwidth limit that may not end out good

**Comment by herohamp** [comment]
Post requests would make crossorigin so much better

**Comment by JacopKane** [comment]
POST requests are fundamental for testing API requests, since one of the biggest purpose of tool for me is testing quicly a remote API with a javascript fiddler

**Comment by technoboy10** [comment]
Looking at implementing this for version 2.

**Comment by HinamoreCh4n** [comment]
POST implementation is a pain in the ass, even PUT and DELETE, get is like just getting and returning a string but POST is a little bit more tricky, plus POST is a bit risky in the security side

**Comment by herohamp** [comment]
@technoboy10 how long till version 2?

**Comment by technoboy10** [comment]
@herohamp I'll be working on it during winter break this year. That means the timeline is roughly Q1 2017 for the release.

**Comment by herohamp** [comment]
Will it be in this repo? As I would be willing to help as I have a ok knowledge of nodeJS

**Comment by technoboy10** [comment]
@herohamp The updated code for the proxy will be on the github repo, yes. I expect that a lot of the work will be infrastructure related, which *won't* be in the repo.

**Comment by herohamp** [comment]
ok

**Comment by danielmcclure** [comment]
Following.

**Comment by phoet** [comment]
not implementing POST will make this service useless for quite some people which is unfortunate but not a big issue as there are other services out there providing similar functionality AND POST!

this is what i'm using right now for running tests against pandorabots.com:

```
curl 'https://cors-anywhere.herokuapp.com/https://www.pandorabots.com/pandora/talk-xml?botid=812ca0c0de36a3ad' --data 'botid=a04d9fbb3e31906d&input=hallo%3F&custid=123' -H 'x-requested-with: curl'
```

**Comment by technoboy10** [comment]
Tracking this in the feature/POST branch.
